[package]
name = "lox"
version = "0.1.0"
authors = ["Pablo Tato Ramos <pabtatoramos@gmail.com>"]
edition = "2018"

[workspace]

[[bin]]
name = "lox"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
lazy_static = "1.4"